### ISSUE TITLE
Input from LED instead of tapping?

### ISSUE THREAD

**Issue by lameller** [DieterVDW/arduino-midi-clock#11]
Hi Dieter

Great project! Very, very close to what I would like to do:-) 

Would it be possible to use the voltage from a blinking LED as the tempo input instead of a tap button?

I found this project where an LED on a Boss Looper pedal is used to drive a sync output:
http://luxmonday.com/2018/07/26/modifying-a-boss-rc-3-to-add-a-korg-sync-output/

This is exactly what I want to do, but I would like to use an Arduino Nano instead of a Pic and have it send Midi Clock instead of Sync.

Could you point me in a direction as to how to convert the voltage drops from the LED's into something that can be used to drive the "tapping" in your sketch?

Hope that my question isn't to confusing:-)

Hope to hear back

Best

Mikkel from Denmark

**Comment by DieterVDW** [comment]
Hi Mikkel!

Well the tap input is just a digital input switching from low to high, so if you connect that to the LED line there's a pretty good chance it would just work I think!
I guess it depends on which voltage the LED gets.. Worst case you might have to amplify that signal first, but I think the arduino interrupt should be able to trigger on whatever voltage that LED receives ...

You should measure what voltage that LED gets in both the ON and OFF states and check if you can trigger a digital input on the Arduino using those voltages. If not, you'll need to do some magic to massage the signal into something the Arduino can use, just like in the page you linked.

The Arduino can definitely measure any voltage between 0 and 5V, so you could maybe solve it by polling the voltage on an analog input. However I don't know how well that would work with the rest of the code which is quite time sensitive...

The nice thing about my current solution is that it triggers an interrupt when the signal goes from HIGH to LOW (or reverse), so I don't need to do polling... That makes it a lot easier.
I don't know how 'sensitive' that interrupt is though, and to what voltages it reacts ..

**Comment by lameller** [comment]
Cool! I am basing it on this guys project:
http://luxmonday.com/2018/07/26/modifying-a-boss-rc-3-to-add-a-korg-sync-output/

The voltage is not directly from the LED, as this graph the other guy did shows. I will just try it out and see what happens:-) 

Thankyou for replying:-)

![Skærmbillede 2019-06-02 kl  20 41 33](https://user-images.githubusercontent.com/47031943/58766964-65687580-8585-11e9-9510-1d67c459bafb.png)

**Comment by DieterVDW** [comment]
Let me know how it goes! Super happy somebody found this and maybe it is of any use! :)
