### ISSUE TITLE
Midi start stop

### ISSUE THREAD

**Issue by goatboyrobbie** [DieterVDW/arduino-midi-clock#13]
Hello Dieter and thanks for sharing your project. I am using it to control some pocket operators which work perfectly via sync. However, I can't seem to get any midi working at all. I'm using a mega so I'm able to debug at the same time fortunately. I have a simple button attached to A1 but it doesn't appear to work and doesn't show in the serial monitor as being pressed.
Do you have any suggestions as to what might not be working?
I should add that I'm using the Dimmer BPM input and not the BPM increase/Decrease which I have omitted.
Should this button also be start and stop for the sync output as well?
Regards
Robbie

**Comment by DieterVDW** [comment]
Do you see anything in the serial monitor?

I see there are 2 definitions set to use pin A1:
#define DIMMER_CHANGE_PIN A1
#define START_STOP_INPUT_PIN A1

Maybe comment out the define for the feature you're not using, that might be where things go wrong.
Or maybe even remove or comment out code for features you're not using.

It's been a long time since I looked at this code, so bear with me :) .

**Comment by goatboyrobbie** [comment]
Yes, I did comment out DIMMER_CHANGE_PIN A1. I commented out that whole feature in fact.
All i have in my serial monitor is Tap with the bpm changes and that works fine. Just no midi. 
My button is wired as it would be for a digital pin but in this case for analog input A1.
Should it be wired differently?
Could the code be changed to read the button from a digital pin instead?

**Comment by DieterVDW** [comment]
It's been a while since I messed around with Arduino's, but I don't see why a digital pin wouldn't work.
It would probably be easier.

You would just need to change the 
> analogRead(START_STOP_INPUT_PIN)

 to the matching digital IO function call...

**Comment by goatboyrobbie** [comment]
I'll give that a go but would you have an idea on how to alter this part to reflect the change to a digital pin?

boolean startStopPressed = (START_STOP_PIN_POLARITY - analogRead(START_STOP_INPUT_PIN)) > 1024 / 2 ? true : false;
  if (startStopPressed && (lastStartStopTime + (DEBOUNCE_INTERVAL * 1000)) < now) {
    startOrStop();
    lastStartStopTime = now;
  }

**Comment by DieterVDW** [comment]
I think it's as simple as:

boolean startStopPressed = digitalRead(START_STOP_INPUT_PIN) == HIGH;

And keep the rest of the code the same...
(I'm assuming debouncing also needs to be done on digital IO...)

Thinking about this it would probably be more logical to handle keypresses in some interrupt handler.
I didn't think anyone else would ever try to use this code so I was lazy 😁 .

**Comment by goatboyrobbie** [comment]
Thanks Dieter. That appears to be working in the serial monitor now. I'm getting start/stop messages now. 
Thanks for your time!
Robbie

**Comment by DieterVDW** [comment]
Awesome!
