### ISSUE TITLE
midi tempo change

### ISSUE THREAD

**Issue by goatboyrobbie** [DieterVDW/arduino-midi-clock#14]
Hello Dieter once again.
If I could trouble you again, would you have an idea on how to sync midi to the tap tempo? It would be great to be able to change the midi tempo along with the sync output for multiple connected devices.
Regards
Robbie

**Comment by DieterVDW** [comment]
Hmm I thought that was how it worked actually.
Tap the tempo and both midi and sync out should follow the new tempo?

**Comment by goatboyrobbie** [comment]
So did I! Funnily enough, I had found a similar project to yours had the same issue. I'll keep going and see if I can work it out.
