### ISSUE TITLE
Receives tap tempo cc value as input

### ISSUE THREAD

**Issue by slowman74** [DieterVDW/arduino-midi-clock#15]
Hi
Your coding has been a great help to my coding. Thank you.
But I have one question to ask.
Your coding is the coding that gets input by tapping the tap tempo switch.
I am composing coding that receives tap as cc value generated from MIDI pedal and outputs MIDI clock.
I would like to ask if there is a way to replace the tabs entered as cc values in your coding.

**Comment by DieterVDW** [comment]
Hi!

You're going to have to add a serial port that is connected to your MIDI in, and then parse MIDI data coming in through that serial device.
I have another project that reads MIDI data and outputs a CV value, you should be able to recycle some code from there:
https://github.com/DieterVDW/arduino-usb-midi-to-CV/blob/master/USB-MIDI-to-CV.ino

Good luck!
