### ISSUE TITLE
Button wiring

### ISSUE THREAD

**Issue by ghost** [DieterVDW/arduino-midi-clock#16]
How is the tap button wired? LittleBits link is dead,
Tried d2 to One side of button and otherside to gnd, 3.3v, 5v, led always blinks same speed, same with start stop button, led never starts or stops, not using digi display so no idea if tempo is changing

**Comment by DieterVDW** [comment]
Oof it's been a while, but I would assume you'd connect one leg to the D2 port, and another to a 5V supply.
The idea being: button pressed -> D2 sees 5v, button not pressed -> D2 sees no voltage.

However, if my memory is not failing me, I think you also need to add a pull-down resistor (ie. a resistor with a high value) on the D2 side of the button connected to ground, to "bleed away" the voltage after a keypress.

**Comment by ghost** [comment]
Thank you! Tap works great now
