### ISSUE TITLE
Possible to use on Nano?

### ISSUE THREAD

**Issue by kcolina** [DieterVDW/arduino-midi-clock#3]
Hey there, I'm pretty new to Arduino but was hoping I could get away with copying your code for this onto the Nano and away I go. However it returns the following on attempting to upload to the board:

> Arduino: 1.6.7 (Mac OS X), Board: "Arduino Nano, ATmega328
> 
> /Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/Kieran/Documents/Arduino/libraries" -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10607 -build-path "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp" -warnings=default -prefs=build.warn_data_percentage=75 -verbose "/Users/Kieran/Downloads/arduino-midi-clock-master/arduino-midi-clock-master/MIDI-Clock/MIDI-Clock.ino"
> /Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/Kieran/Documents/Arduino/libraries" -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10607 -build-path "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp" -warnings=default -prefs=build.warn_data_percentage=75 -verbose "/Users/Kieran/Downloads/arduino-midi-clock-master/arduino-midi-clock-master/MIDI-Clock/MIDI-Clock.ino"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM" "/Users/Kieran/Documents/Arduino/libraries/TimerOne/TimerOne.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/dev/null"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
> "/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino5/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
> "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++" -c -g -Os  -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/eightanaloginputs" "-I/Users/Kieran/Documents/Arduino/libraries/TimerOne" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM" "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp" -o "/var/folders/tk/7s1jqwsd1lq_r5qcr3lhy_gw0000gn/T/buildae124e3407d14aaf4ea55552a5914329.tmp/sketch/MIDI-Clock.ino.cpp.o"
> /Users/Kieran/Downloads/arduino-midi-clock-master/arduino-midi-clock-master/MIDI-Clock/MIDI-Clock.ino: In function 'void setup()':
> MIDI-Clock:50: error: 'Serial1' was not declared in this scope
>    Serial1.begin(31250);
>    ^
> /Users/Kieran/Downloads/arduino-midi-clock-master/arduino-midi-clock-master/MIDI-Clock/MIDI-Clock.ino: In function 'void startOrStop()':
> MIDI-Clock:135: error: 'Serial1' was not declared in this scope
>      Serial1.write(MIDI_START);
>      ^
> MIDI-Clock:138: error: 'Serial1' was not declared in this scope
>      Serial1.write(MIDI_STOP);
>      ^
> /Users/Kieran/Downloads/arduino-midi-clock-master/arduino-midi-clock-master/MIDI-Clock/MIDI-Clock.ino: In function 'void sendClockPulse()':
> MIDI-Clock:145: error: 'Serial1' was not declared in this scope
>    Serial1.write(MIDI_TIMING_CLOCK);
>    ^
> Using library TimerOne at version 1.1 in folder: /Users/Kieran/Documents/Arduino/libraries/TimerOne 
> Using library EEPROM at version 2.0 in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/EEPROM 
> exit status 1
> 'Serial1' was not declared in this scope

Is this because the Nano only has one Serial port? Is there any way around this? 

Cheers!

**Comment by DieterVDW** [comment]
Hi!

Should be possible without too many problems.
The Arduino Leonardo was the first Arduino I ever had, and indeed it is very easy to work with Serial communication on that board because you indeed have a separate serial device for debugging through the console.

I recently also bought a Arduino Uno, and have worked to get it working on that board too.
(Very annoying if you can't use the debug console grr!)
But check out the branch 'arduino-uno', that _should_ contain the latest code working on devices which have only one serial device... Let me know if that works for you!

**Comment by kcolina** [comment]
Hey thanks for that, but still no luck :(

Is there anything I could be missing?

**Comment by DieterVDW** [comment]
Still getting a compile error?
Or what is going wrong now?

**Comment by kcolina** [comment]
Uploads perfectly but LED isn't displaying tempo and no output to midi.

**Comment by DieterVDW** [comment]
I'm 100% sure it has worked on my Uno already, but I indeed had a lot more
problems to get the program to work smoothly.
When I upload to my Leonardo board, it works 95% of the times. Uploading to
Uno gave me only 10% success rate or something ...
I have no idea why, and because you can't use serial communications and
debug console at the same moment, that's a very annoying problem to debug
:| .
Can you try uploading a few times and see if you have any luck at some
point?

I'll have a look this evening to see if I can get it going on my Uno.
There must be a way to do serial communications programming on an Arduino
and still be able to have some kind of debugging I guess, but I'm not aware
of it yet.
I'm also still finding my way in the Arduino world :) .

I hope I can help you this evening!

**Comment by kcolina** [comment]
Awesome thanks! I'll keep trying!

**Comment by DieterVDW** [comment]
Well, it works perfectly here now actually...

I also see no real reason why it wouldn't work on a Nano board.

Are you sure you wired everything correctly?
Feel free to post a (clear :) ) picture of your setup and I'll give it a
second pair of eyes .

Should work though I think!

**Comment by kcolina** [comment]
Pretty sure I've got it all wired correct. I'm scoping the MIDI output before connecting to any equipment (and I'm also waiting on stock of 220ohm resistors for the MIDI connector!) so that is the only thing that is wrong however it should still be outputting something and the LED should be blinking right?

Momentary on push button is connected to Rx and ground (grey wire).
LED is connected to A5 via resistor and ground (this is working fine with Blink on D13 so I know LED and board are working).
4.9V in to VIN.
I'll add a potentiometer once I've got the basics working. From what I understand with Arduino is pots connect like so: One side to 5V, Wiper to A0 (to suit your code) and other side to Ground. Correct?

![nano_midi](https://cloud.githubusercontent.com/assets/17265874/13097666/fe9a23e0-d587-11e5-8deb-f51bdebc375b.JPG)

**Comment by kcolina** [comment]
Duh LED now on D5 and blinking but not in time with button press and pot now in place - doesn't set tempo nicely though :/

**Comment by kcolina** [comment]
To be more specific - turning the pot does indeed change the tempo of the LED but is not always a stable constant pulse. What value of pot do you recommend I use? Button press doesn't actually seem to be doing anything.

**Comment by kcolina** [comment]
Ok so I've swapped the pot out, thats working brilliantly now and I can sync it to a metronome at both the min and max BPM set in the code. But still nothing from the switch :(

**Comment by DieterVDW** [comment]
Quick comment without having been able to look at it in depth yet:
First thought:
Make sure you connect the tap button with a pull-down resistor, otherwise
the pin reads a floating value and will continuously read false taps!

**Comment by kcolina** [comment]
So I just add a 10k from the Rx pin to ground? Other side of switch is going to 5V correct?

**Comment by DieterVDW** [comment]
Yep, just a 'big' resistor on the tap pin.
10k should be fine I think.

**Comment by kcolina** [comment]
Still no luck. Is it essential to use the Rx pin as the tap input? I've attached an updated photo, hopefully you can spot something I've done wrong!
- Rx connected to ground via 10k resistor and to switch via grey wire.
- Other side of switch connected to 5V via orange wire.
- Everything else in correct place and working as expected.

Also interested in adding an i2c OLED display to show the current BPM. Any thoughts on how to add this?

![nano_midi2](https://cloud.githubusercontent.com/assets/17265874/13133610/c3b20240-d661-11e5-91b2-7733a58a2218.JPG)

**Comment by DieterVDW** [comment]
Hmm well the potentiometer and tap input are kind of complimentary (and
they can work against eachother of one of both is causing trouble).

You can perfectly disconnect either one of both pins for testing, just make
sure to ground the disconnected pin to make sure the pin is 'quiet' and not
generating floating readings.
Try that and see if that helps ... ?

A debug console is so handy :) . Love the Leonardo Arduino for this, so
nice to just see debug info while testing!
(Not helping though, sorry :p ).

Have never used i2c or a display with Arduino yet! Still on my TODO list,
so can't help you with that I'm afraid :s .
Let me know if you get that working (and submit a pull-request please! :) ).

**Comment by kcolina** [comment]
Hmm, with pot out and pin grounded still no luck with button tap. I've triple checked its set to the right pin in the code and on the board and to me it seems correct so not sure what to do next! Working perfect with just the pot.

Also possibly worth mentioning, if I connect the switch between Rx and ground without the 10k to ground from Rx the Rx LED recognises each button press. Should that Rx LED also illuminate with the switch across Rx with 10k to ground and 5V out?

Just to make sure - with the button connected to Rx what pin should that translate to in the code? Your original code reads "#define TAP_PIN 2".

**Comment by kcolina** [comment]
Ha ok, I got it. Your instructions on the readme said to connect a button to D0. After learning some more about interupts I discovered D2 & 3 are the interupts so I connected to D3 and changed the TAP_PIN to 3.

Seems to be working fine now!

It would be great if the LED would update as soon as 3 taps had been reached, rather than when it detects that the button is no longer being tapped. Is that possible? Reason for this is I'll be using it live and will be tapping the tempo while playing with a delay that this clock will be controlling. If I were to continue tapping after 3 taps it won't update my delay time until I stop tapping right? Ideally the time would change on each tap after the minimum of 3.

**Comment by DieterVDW** [comment]
Indeed, the documentation was wrong :( .
I think I originally used D0, but then switched to D2 so I could use D0 for MIDI input in the future (which I actually just got working and implemented!).

It should be pretty simple to modify the tap tempo to just update after 3 taps.
Currently the algorithm goes something like this:
- Store timestamp of first tap
- For every tap: store timestamp of the last tap
- After a timeout: calculate the BPM based on #taps and time between first and last tap (so averaging out over all taps)

You can pretty easily modify this to immediately update the BPM after 3 taps. I don't know how accurate that will be though. I would expect it to be harder to tap the correct BPM.
Modify at own risk, I take no responsability for failed performances :D .

I also have the plan to use this live to set the temp, but haven't tried yet (I still have to build it into a case).
So don't expect the code to be flawless yet, I expect some tweaking will still be needed.

**Comment by kcolina** [comment]
I just had the notes about pins from the documentation so stuck in my head as I read that before I saw the code! I probably should have made more effort in learning about Arduino before getting stuck in haha.

Cool! We'll tweak together! I'll let you know how i get on with the display and any other changes.

Chur!

**Comment by DieterVDW** [comment]
Actually I have a band gig in march where I could really use a tap tempo. So I have a deadline for trying to make something 'gig-ready' :) .
I already have all the components, I only need to fit everything in the box. I'm a lot better at prototyping then at drilling holes and DIY stuff though...

Keep me posted! I'll do the same! :)

**Comment by kcolina** [comment]
What's your band?! I play in a 3-piece sonic/post-rock band in New Zealand. Have a peak if you're interested! www.facebook.com/nobroadcast

See I'm pretty great at the physical build and unique enclosures with basic-mid level electronics skill (esp as tour tech - so many quick side of stage repairs!) but am very new to microprocessors/Arduino. I think it's pretty neat that I can put something together relatively cheap that was created while learning something new, and getting help from the likes of yourself!

**Comment by DieterVDW** [comment]
I play in a cover band: http://www.simonsix.be , mostly for fun though.

I'm the exact opposite: computer programmer by profession, just started
tinkering with electronics and pretty average at all things DIY...

Very happy to see somebody is interested in this!

**Comment by DieterVDW** [comment]
Ok if I close this issue? Any more luck?

**Comment by DieterVDW** [comment]
BTW I added support for a TM1637 led display, check it out!

**Comment by kcolina** [comment]
Yup working perfectly! Going to be adding jacks to suit tap input on pedals
like boss dd7 as well as midi! Awesome about the display!

Kieran

**Comment by DieterVDW** [comment]
Ok, going to close this then for the sake of 0 open issues :) .
